language: node_js
matrix:
  fast_finish: true
  include:
  - os: osx
    osx_image: xcode9.2
    node_js: 8
  - os: linux
    node_js: 8
    env:
    - CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
addons:
  apt:
    packages:
    - python3
    - python3-pip
    - snapd
cache: yarn
before_install:
- openssl aes-256-cbc -K $encrypted_9b138b9d5184_key -iv $encrypted_9b138b9d5184_iv -in snapcraft_login.enc -out snapcraft_login -d
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo snap install snapcraft --classic; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then snap run snapcraft login --with snapcraft_login; fi
before_script:
- yarn lint
script:
- yarn dist
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi
- yarn test
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then yarn directory:install && yarn directory:test; fi
- if [ "$TRAVIS_OS_NAME" == "linux" -a "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then yarn directory:install && yarn directory:pack && yarn directory:publish; fi
deploy:
  on:
    tags: true
  provider: script
  script: bash snapcraft_deploy.sh
  skip_cleanup: true
notifications:
  email: false