language: node_js
matrix:
  fast_finish: true
  include:
  - os: osx
    osx_image: xcode9.2
    node_js: 8
  - os: linux
    node_js: 8
    env:
    - CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
addons:
  apt:
    packages:
    - python3
    - python3-pip
cache: yarn
before_script:
- yarn lint
script:
- yarn dist
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi
- yarn test
- if [ "$TRAVIS_OS_NAME" == "linux" -a "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then yarn directory:install && yarn directory:test && yarn directory:pack && yarn directory:publish; fi
