language: node_js
node_js: 12
os: osx
osx_image: xcode10.2
cache: yarn
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install p7zip; fi
before_script:
- npm install -g npx
- yarn template:install
- yarn lint
script:
- yarn dist
- yarn catalog:install && yarn catalog:test
- if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then yarn catalog:pack && yarn catalog:publish; fi
notifications:
  email: false
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: s3.getwebcatalog.com
  local-dir: catalog/dist
  upload-dir: apps
  acl: public_read
  skip_cleanup: true
  on:
    repo: quanglam2807/webcatalog
branches:
  only:
    - master
    # Ruby regex to match tags. Required, or travis won't trigger deploys when
    # a new tag is pushed. Version tags should be of the form: v0.1.0
    - /^v\d+\.\d+\.\d+.*$/